### https://github.com/anew7237/DOCKER-alpine3.9.x-demo/alpine3.9.x-anew

FROM anew7237/alpine3.9.x-auto:latest
ARG ALPINE_IMAGE_TAG="3.9.x"
ARG ALPINE_X_SUBNAME="testresty"
ARG ALPINE_X_VERSION="20190718a"
ARG ALPINE_X_MARKING="201907180000"


ARG RESTY_ADD_PACKAGE_BUILDDEPS=""
ARG RESTY_ADD_PACKAGE_RUNDEPS=""

LABEL description="Alpine ${ALPINE_IMAGE_TAG} + AnewPackage" \
	maintainer="Andrew Hsieh<anew7237@gmail.com>" \
	ALPINE_X_${ALPINE_X_SUBNAME}_version="${ALPINE_X_VERSION} - ${ALPINE_X_MARKING}" \
	ALPINE_X_${ALPINE_X_SUBNAME}_add_package_builddeps="${RESTY_ADD_PACKAGE_BUILDDEPS}" \
	ALPINE_X_${ALPINE_X_SUBNAME}_add_package_rundeps="${RESTY_ADD_PACKAGE_RUNDEPS}" \
	ALPINE_X_${ALPINE_X_SUBNAME}_resty_test="copy /x_resty/ to /x_resty/" \
	ALPINE_X_${ALPINE_X_SUBNAME}_git="apk add git"

RUN echo "##### ##### ##### #####" >> /_dockerDebug.log \
	&& mkdir -p /x_resty && chmod 700 /x_resty \
	&& echo "$(date -u) ${ALPINE_X_MARKING} Alpine${ALPINE_IMAGE_TAG}-${ALPINE_X_SUBNAME}:${ALPINE_X_VERSION}" >> /_dockerDebug.log

COPY _COPY_/x_resty/sregex.20190711.tar.gz				/x_resty/sregex.20190711.tar.gz
COPY _COPY_/x_resty/replace-filter-nginx-module.20190711.tar.gz		/x_resty/replace-filter-nginx-module.20190711.tar.gz
COPY _COPY_/x_resty/ngx_brotli.20190711.tar.gz				/x_resty/ngx_brotli.20190711.tar.gz
COPY _COPY_/x_resty/openresty-1.15.8.1.tar.gz	/x_resty/openresty-1.15.8.1.tar.gz
COPY _COPY_/x_resty/openssl-1.1.1c.tar.gz	/x_resty/openssl-1.1.1c.tar.gz
COPY _COPY_/x_resty/pcre-8.42.tar.gz		/x_resty/pcre-8.42.tar.gz

RUN apk update \
	&& apk add --no-cache git \
    && apk add --no-cache --virtual .build-deps \
        build-base \
        coreutils \
        curl \
        gd-dev \
        geoip-dev \
        libxslt-dev \
        linux-headers \
        make \
        perl-dev \
        readline-dev \
        zlib-dev \
        ${RESTY_ADD_PACKAGE_BUILDDEPS} \
    && apk add --no-cache \
        gd \
        geoip \
        libgcc \
        libxslt \
        zlib \
        ${RESTY_ADD_PACKAGE_RUNDEPS} \
	&& rm -rf /var/cache/apk/*.apk && rm -rf /tmp/* && echo "$(date -u) ${ALPINE_X_MARKING} !!!DONE!!!" >> /_dockerDebug.log
