### https://github.com/anew7237/DOCKER-alpine3.9.x-demo/alpine-openresty

FROM anew7237/alpine-openresty:20190904a
ARG ALPINE_IMAGE_TAG="3.9.x"
ARG ALPINE_X_SUBNAME="php7resty"
ARG ALPINE_X_VERSION="20190904a"
ARG ALPINE_X_MARKING="201909040000"


ARG PHP7_MODULES="\
php7-common@php7codecasts \
php7-fpm@php7codecasts \
##php7-cgi@php7codecasts \
##php7-apache2@php7codecasts \
##php7-doc@php7codecasts \
##php7-dev@php7codecasts \
\
##php7-sodium@php7codecasts \
php7-bcmath@php7codecasts \
php7-bz2@php7codecasts \
php7-calendar@php7codecasts \
php7-ctype@php7codecasts \ 
php7-curl@php7codecasts \
##php7-dba@php7codecasts \
php7-dom@php7codecasts \
##php7-embed@php7codecasts \
##php7-enchant@php7codecasts \
php7-exif@php7codecasts \
php7-ftp@php7codecasts \
php7-gd@php7codecasts \
php7-gettext@php7codecasts \
##php7-gmp@php7codecasts \
php7-iconv@php7codecasts \
##php7-imap@php7codecasts \
php7-intl@php7codecasts \
php7-json@php7codecasts \
php7-ldap@php7codecasts \
##php7-litespeed@php7codecasts \
php7-mbstring@php7codecasts \
php7-mysqli@php7codecasts \
php7-mysqlnd@php7codecasts \
##php7-odbc@php7codecasts \
php7-opcache@php7codecasts \
php7-openssl@php7codecasts \
php7-pcntl@php7codecasts \
php7-pdo@php7codecasts \
##php7-pdo_dblib@php7codecasts \
php7-pdo_mysql@php7codecasts \
##php7-pdo_pgsql@php7codecasts \
php7-pdo_sqlite@php7codecasts \
##php7-pear@php7codecasts \
##php7-pgsql@php7codecasts \
php7-phar@php7codecasts \
##php7-phpdbg@php7codecasts \
php7-posix@php7codecasts \
##php7-pspell@php7codecasts \
php7-session@php7codecasts \
##php7-shmop@php7codecasts \
##php7-snmp@php7codecasts \
php7-soap@php7codecasts \
php7-sockets@php7codecasts \
php7-sqlite3@php7codecasts \
##php7-sysvmsg@php7codecasts \
php7-tidy@php7codecasts \
php7-wddx@php7codecasts \
php7-xml@php7codecasts \
php7-xmlreader@php7codecasts \
##php7-xmlrpc@php7codecasts \
php7-xsl@php7codecasts \
php7-zip@php7codecasts \
php7-zlib@php7codecasts \
\
##php7-amqp@php7codecasts \
php7-apcu@php7codecasts \
##php7-ast@php7codecasts \
##php7-ds@php7codecasts \
php7-imagick@php7codecasts \
###php7-mailparse@php7codecasts \
php7-memcached@php7codecasts \
##php7-mongodb@php7codecasts \
##php7-msgpack@php7codecasts \
##php7-psr@php7codecasts \
##php7-phalcon@php7codecasts \
php7-redis@php7codecasts \
###php7-ssh2@php7codecasts \
##php7-swoole@php7codecasts \
##php7-timecop@php7codecasts \
##php7-libsodium@php7codecasts \
##php7-scalar_objects@php7codecasts \
##php7-secp256k1@php7codecasts \
##php7-xdebug@php7codecasts \
\
##argon2@php7codecasts \
##argon2-dev@php7codecasts \
##libargon2@php7codecasts \
##secp256k1@php7codecasts \
"

LABEL description="Alpine ${ALPINE_IMAGE_TAG} + OpenResty(TarBall) + PHP7(Repositories by CODECASTS)" \
	maintainer="Andrew Hsieh<anew7237@gmail.com>" \
	ALPINE_X_${ALPINE_X_SUBNAME}_version="${ALPINE_X_VERSION} - ${ALPINE_X_MARKING}" \
	ALPINE_X_${ALPINE_X_SUBNAME}_php7_modules="${PHP7_MODULES}" \
	ALPINE_X_${ALPINE_X_SUBNAME}_php7="apk add php7@php7codecasts(Repositories by CODECASTS)"

RUN echo "##### ##### ##### #####" >> /_dockerDebug.log \
	&& mkdir -p /x_script && chmod 700 /x_script \
	&& mkdir -p /etc/php && chmod 775 /etc/php \
	&& mkdir -p /etc/php/fpm.d && chmod 775 /etc/php/fpm.d \
	&& adduser -S -D -H -h /x_husers -s /bin/false -g "phpfpm" -G husers -u 992 phpfpm \
	&& echo "$(date -u) ${ALPINE_X_MARKING} Alpine${ALPINE_IMAGE_TAG}-${ALPINE_X_SUBNAME}:${ALPINE_X_VERSION}" >> /_dockerDebug.log

COPY _COPY_/x_script/*				/x_script/
COPY _COPY_/x_config/php.evn			/x_config/php.evn
COPY _COPY_/etc/php/php.ini			/etc/php/php.ini
COPY _COPY_/etc/php/fpm.ini			/etc/php/fpm.ini
COPY _COPY_/etc/php/fpm.d/9000.ini		/etc/php/fpm.d/9000.ini
COPY _COPY_/etc/supervisor.d/30-php-fpm.ini	/etc/supervisor.d/30-php-fpm.ini


# PHP Repositories for Alpine - by CODECASTS
# https://github.com/codecasts/php-alpine

COPY _COPY_/etc/apk/keys/php-alpine.rsa.pub	/etc/apk/keys/php-alpine.rsa.pub

RUN apk --no-cache add ca-certificates imagemagick \
	&& curl https://dl.bintray.com/php-alpine/key/php-alpine.rsa.pub -o /etc/apk/keys/php-alpine.rsa.pub \
	&& echo "@php7codecasts https://dl.bintray.com/php-alpine/v3.9/php-7.3" >> /etc/apk/repositories \
	&& apk add --update --no-cache php7@php7codecasts ${PHP7_MODULES} \
#	&& apk add --update --no-cache php7@php7codecasts php7-fpm@php7codecasts php7-json@php7codecasts php7-phar@php7codecasts php7-iconv@php7codecasts php7-mbstring@php7codecasts php7-openssl@php7codecasts php7-zlib@php7codecasts \
	&& ln -s /usr/bin/php7 /usr/bin/php \
	&& ln -s /usr/sbin/php-fpm7 /usr/bin/php-fpm \
	&& ln -s /etc/php7/conf.d /etc/php/conf.d \
	&& rm -rf /var/cache/apk/*.apk && rm -rf /tmp/* && echo "$(date -u) ${ALPINE_X_MARKING} !!!DONE!!!" >> /_dockerDebug.log


# Imagick support file types
#RUN apk add --no-cache imagemagick

#RUN mkdir -p /src && \
#  ln -s /etc/php7 /etc/php && \
#  ln -s /usr/bin/php7 /usr/bin/php && \
#  ln -s /usr/sbin/php-fpm7 /usr/bin/php-fpm

# Add Composer
RUN curl https://getcomposer.org/installer -o /tmp/composer-installer && php /tmp/composer-installer --install-dir=/usr/local/bin --filename=composer && rm -f /tmp/composer-installer

# Supervisor
#ADD conf/supervisord.conf /etc/supervisord.conf
#ADD conf/supervisor.d /etc/supervisor.d
#RUN mkdir -p /etc/supervisord-enabled && mkdir -p /etc/supervisord-worker

# Scripts
#ADD scripts/start-web.sh /start-web.sh
#RUN chmod 755 /start-web.sh
#ADD scripts/start-worker.sh /start-worker.sh
#RUN chmod 755 /start-worker.sh

#ADD conf/nginx.conf /etc/nginx/nginx.conf

#ADD conf/nginx-site.conf /etc/nginx/sites-enabled/site.conf
#ADD dependencies/nginx-custom.php /usr/local/bin/nginx-custom

# Test Nginx
#RUN nginx -c /etc/nginx/nginx.conf -t

## PHP
#ADD conf/php-fpm.conf /etc/php/php-fpm.conf
#ADD conf/php.ini /etc/php/php.ini
#ADD conf/php-www.conf /etc/php/php-fpm.d/www.conf

# Test PHP-FPM
#RUN /usr/bin/php-fpm --fpm-config /etc/php/php-fpm.conf -t


### ### ANEW7237 START ### ###

# Test Nginx
RUN nginx -c /etc/nginx/conf/nginx.conf -t

# Test PHP-FPM
RUN /usr/bin/php-fpm --fpm-config /etc/php/fpm.ini -t
